# Generated by Django 4.2.7 on 2023-12-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="fffffff", max_length=1024)),
                ("description", models.TextField(default="fffffff")),
                ("is_published", models.BooleanField()),
                ("published_at", models.DateField()),
                ("rating", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Athletics", "Athletics"),
                            ("Team_sport", "Team Sport"),
                            ("Individual_sport", "Individual Sport"),
                            ("Water_sport", "Water Sport"),
                            ("Skiing_sport", "Skiing Sport"),
                        ],
                        default="Athletics",
                        max_length=64,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="images/default.jpg", upload_to="images/"
                    ),
                ),
            ],
        ),
    ]
