# Generated by Django 4.2.7 on 2023-11-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Stories', 'Stories'), ('Science', 'Science')], default='Health', max_length=50),
        ),
    ]
