# Generated by Django 4.2.7 on 2023-11-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
