# Generated by Django 4.2.7 on 2023-11-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_remove_blog_image_blog_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='images',
            new_name='image',
        ),
    ]
