# Generated by Django 4.2.7 on 2023-11-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Art', 'Art'), ('News', 'News')], default='Art', max_length=2048),
        ),
    ]
