# Generated by Django 4.2.7 on 2023-11-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='image/'),
        ),
    ]
