# Generated by Django 4.2.7 on 2023-11-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Personal', 'Personal')], default='Personal', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog1',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
