# Generated by Django 4.2.7 on 2023-11-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog1_category_alter_blog1_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='image',
            field=models.ImageField(default='images/blog.jpeg', upload_to='images/'),
        ),
    ]
