# Generated by Django 4.2.7 on 2023-11-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_content_blog_is_published_blog_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Art', 'Art'), ('Food', 'Food')], default='', max_length=156),
        ),
    ]
