# Generated by Django 4.2.7 on 2023-11-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='img/default.png', upload_to='img/'),
        ),
    ]
