# Generated by Django 4.2.7 on 2023-11-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_op', '0003_alter_published_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='published',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
