# Generated by Django 4.2.7 on 2023-11-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_op', '0005_alter_published_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='published',
            name='blog_content',
            field=models.CharField(choices=[('News', 'News'), ('Story', 'Story'), ('Poetry', 'Poetry')], default='Story', max_length=56),
        ),
        migrations.AddField(
            model_name='published',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
