# Generated by Django 4.2.7 on 2023-11-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField()),
                ('published_at', models.DateField()),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('News', 'News'), ('Marketing', 'Marketing'), ('Entrepreneurship', 'Entrepreneurship')], max_length=65)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
