# Generated by Django 4.2.7 on 2023-11-23 10:53

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('politics', 'Politics'), ('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to=blog.models.random_image_filename),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
