# Generated by Django 4.2.7 on 2023-11-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('movies', 'Movies'), ('books', 'Books'), ('else', 'Else')], default='else', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='poster',
            field=models.ImageField(default='img/default.jpg', upload_to='img/'),
        ),
    ]
