# Generated by Django 4.2.7 on 2023-11-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category_blog_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
