# Generated by Django 4.2.7 on 2023-11-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Dialogues', 'Dialogues'), ('Articles', 'Articles'), ('Stories', 'Stories'), ('Fantasy', 'Fantasy')], default='Articles', max_length=64),
            preserve_default=False,
        ),
    ]
