# Generated by Django 4.2.7 on 2023-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Makeup', 'Makeup'), ('Movie', 'Movie'), ('Celebrities', 'Celebrities'), ('Care', 'Care'), ('Places', 'Places')], default='Movie', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='poster',
            field=models.ImageField(default='images/blog.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
