# Generated by Django 4.2.7 on 2023-11-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Published_at',
            new_name='published_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Educationl', 'Educationl'), ('Art', 'Art'), ('Cultual', 'Cultual'), ('Podcast', 'Podcast'), ('Corporate', 'Corporate')], default='Cultural', max_length=70),
        ),
    ]
