# Generated by Django 4.2.7 on 2023-11-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_published_at_blog_published_at_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='poster',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
