# Generated by Django 4.2.7 on 2023-11-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_info_category_info_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='category',
            field=models.CharField(choices=[('Comment', 'Comment'), ('Complaint', 'Complaint'), ('Suggestion', 'Suggestion')], default='Action', max_length=64),
        ),
    ]
