# Generated by Django 4.2.7 on 2023-11-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_info_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='category',
            field=models.CharField(choices=[('Comment', 'Comment'), ('Complaint', 'Complaint'), ('Suggestion', 'Suggestion')], default='Comment', max_length=64),
        ),
        migrations.AlterField(
            model_name='info',
            name='poster',
            field=models.ImageField(default='images/content.jpeg', upload_to='images/'),
        ),
    ]
