# Generated by Django 4.2.7 on 2023-11-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Horro', 'Horro'), ('Fantasy', 'Fantasy')], default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='blog/images'),
        ),
    ]
