# Generated by Django 4.2.7 on 2023-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_category_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Caltural', 'Caltural'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Comedy', 'Comedy')], default='General', max_length=64),
        ),
    ]
