# Generated by Django 4.2.7 on 2023-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_category_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='imgs/default.png', upload_to='imgs/'),
        ),
    ]
