# Generated by Django 4.2.7 on 2023-11-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='poster',
        ),
    ]
