# Generated by Django 4.2.7 on 2023-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Personal blogs', 'Personal Blogs'), ('Lifestyle', 'Lifestyle'), ('News blogs', 'News Blogs'), ('technology', 'Technology')], default='Lifestyle', max_length=64),
        ),
    ]
